CREATE TABLE `product_warehouse` (
     `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
     `product_id` BIGINT UNSIGNED NOT NULL,
     `warehouse_id` BIGINT UNSIGNED NOT NULL,
     `quantity` INT NOT NULL DEFAULT 0,
     `reserved_quantity` INT NOT NULL DEFAULT 0,
     `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);