CREATE TABLE `order_item` (
      `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      `order_id` BIGINT UNSIGNED NOT NULL,
      `product_id` BIGINT UNSIGNED NOT NULL,
      `warehouse_id` BIGINT UNSIGNED NOT NULL,
      `qty` INT NOT NULL,
      `price` DECIMAL(12,2) NOT NULL,
      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);